language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  # BINTRAY_USER
  - secure: kQVNXrxnAQ268HQIcrfno98GlP4YQB5NoqUaicVA9KtkfZ4AUJWLVN/RzaB2xDhyOgEEclkJ0JsrnJ09PLNmQTlYa4dkFmg4+E7HbT6qyfGn3Mng9zFnk2XYFWvhR8ErutefI6Ixma/xJnWrWJ+hVLCUNTRc8FRDCn6W2dey+2v13cAog6wwosRf7584Kw6M3Ym2iZ9hhXPAXKzYpjiZ7zj/jNo2QCGGJ5Hhh46Mrr/qzZDsXx1R8IyWoosk7c7zzjV3b9ElMG2HIYnBelvtAY3NzbKl0w/3GiKAhDGNjHwM6KlUmdOswMxNGp9I/CG6jua264aNK7jXcpFDO/TWQNAccg2gSIKyUoEksl1zaaPs1rTQTa0J7VWrvkIQw1jQfKY7ouQL502bIQsoSanmfmUmgCTNKrcpVqzwbPTsmrcjr68q1teZ8JEU7MMEpMhJmKh6QF5udM1H+2X9mRLjZIURcw09p6m9s6jTL7+c3K/8p/SUZITu4qTf1VF8s+hHMrTj4m7gWloKxraJODXO9iPmEqd6pjb+1bQrbKSmZlbi2NAvVO5GuoL0aJFgKn07rBMaI/RKg7gyE3DLEMAJtl9D8EJn1ezGoQBQQSoUUiIzmb3SkVFB+bVE3eIDxauDHdsEnDXzgCDIbk1S5WYf4pck7t/4x8ucYOqKnC05e7U=
  # BINTRAY_KEY
  - secure: MQsN7rBYWRJYoGUkhwGqPz6tpWrK9nCq6hlgX5R33h0PfTgTvhdD3aHtDg5bGtRgaPhXvFy1Ib04K6ZkqFa4dJ7USSRNoumAYPyaXdF2oUl2XUjOFcJwCvTU0COCD5hypkhXC3Lv6kl0lvkpk/w7O4a2nVsUkG3OjHvx6o4q0ZN920SrWhJTIfa+uqP5a8PNQmvCTVTx40azysuVQ7ifoizBXVcX+jmbJHYgAEHUwJFHYMCfzaRJL1mtBnT2sEUU0IFU+jseKz602UnEvbNDmDDWh5/yT1mv7fT25dQvAPvrr63tHZDv2GzqO3tdm79OdUSEXN5bjRDp+TEI0XjLWUh8P+NUv+WYLS//XmsILoPxhDCtE+rfrNrUmCtVd/pWbLoI7/mPxsxDEuv9JLFL4gdiNV3Wp3vnHiTReetBUrN/vcMAa/YUVMloNK0IpUi2qEqYxFw+Ry7trZ87RrEjmUYiFI2dyy7phuR4H/8WZUxvyzpUQj10oB6UUdTvt2a70zi4S39vazTTj7WzdZnvedOv6CCN5f+Skyr0W45ZJLygaAZmVHmckWMYGKIG7UR76eZAoohrHaD611kT3OUXVQ9mpOOqC7LHF23MWE5EbAhw5/CEXetXzLagFWrV26Ft/tfOTVAbqiGYk6LTA5MFaiH589VSOmg1+ZtVdgtaZ54=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
