language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: KrDaNbfM91pWQioPYzL8dSZdSLl4eIAu+aBg92bT7F0+0YO1f65/J4Gl2cckRbRAmaOAZHBTLiIPcSy6NRqwvYyzB8cALmtuwHC2T218vVa51LUemcPNRqiF5nmDf7ZjrptoqzfJFmqOq1uub/iuN8G+GB6hPcVhPHhFMiU9CIxpqTO//FDW+ny8NZR2vmhrRb1EbPUf3vAIM45tTCj4EvN8iGLdj20Rso68pb37Esl2VtTHKbZaLFnBwBbNYCXL5g+fg+hCsG0DYhP/FDoq8J8HhfdHPN6Pa0j6Vcnp51vIoOX9WWLm1BZR4yGS88LSVaNQDlnBdRdwMl9z8BBi4ipLTon2NIwPoDKmRJzRkTiDoYy9HnMAZZY6XMbZba8YNoHOnvVW+gWWOm3arzf7RmaoWtiJU1l0xcIjd9s0a3EooWGunAaJJrQTiVS4gMbbhuQWyWrlZ7PvDkxHYjXz1MupIierbBGM79hZpc6D0S7UL1D3QUsDmE8rGRjMRcwSMjRpCy2qMFzpUcJiCXGitYC8wQq5ycWDGQdqmwTOZw7WhSbWLq1CaEijpW48A1CcVUqTnCDd/LcILl8i5L4vzsx0i2U81TSw+OPS6Lf4JSzsSJpi9ZwoUm4qVB1+6dNUTlZ3J+GULdSeZVXlQw8f3dYV7rIZAbQzjJ5F/oobyCI=
  - secure: V3ocecv0AQgVO0usFyVLdGlUu57yd9RdI1cJvZ36TURE6OXGZoiD/F2j3oCUdnKMEt1mzcWk2JMvNihehU8tvbxYAvoyhlG+JFt05R452tGwOiaWnTw999ub/kBmt+ebMx0xqLREXBArEJgYpq5xETtAX1PQ1eIuKqmiin2FnsS8RMndxc7+8GFR//RhG3Tf3dJPVTXy/LBW+rAinNOxbUykwvp4NRbNN+anQ3B2U9ytjUYuR4Zgc1CjuOQ4z9nEZa4jCYVJob691zrTqpS1drdQj/ldJU7HDvIKhh+k4Obf2DJMOmVv+3IFHy4ycA1pE73/vL3gSHLEqi486j6vsDcQt6hNI698aU09D/NmGeC2yJfIAogAzHIS9IZUesPZsgD/x0qzv/+U/GE5g5C29IT8FV+fVj1Sh7x2SgL2B2ciiMMAbPiP2B/FMFcSAX9z3ll+P7HXJDkDC+sq+iSOYnZh9LZZ1zWXzi8TMvkZlZvVN3kg+Q8p+6NQhf2BbNYl54c1GLOqnmqQ/EMOXhXhkDGUCxmgbWED+IgwbZsUVwrsmp1EDhkelyjYTf0Ft7lfILQvEzgELVPXc9Gw5bKfeHzftOiucI+kUV7QjLx9wbWD0fLO2ZP9Rv8HpVIQVrI/a3n4qMS3ySrYe6i3LvLx3iVAevhT8DSvrDC+c4ZjGgM=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
